---
- name: Create dest directories
  file: path={{local_release_dir}}/{{item.dest|dirname}} state=directory recurse=yes
  with_items: downloads

- name: Download items
  get_url:
    url: "{{item.url}}"
    dest: "{{local_release_dir}}/{{item.dest}}"
    sha256sum: "{{item.sha256 | default(omit)}}"
  with_items: downloads

- name: Extract archives
  unarchive:
     src: "{{ local_release_dir }}/{{item.dest}}"
     dest: "{{ local_release_dir }}/{{item.dest|dirname}}"
     copy: no
  when: "{{item.unarchive is defined and item.unarchive == True}}"
  with_items: downloads
