---
- hosts: downloader
  sudo: no
  roles:
    - { role: download, tags: download }

- hosts: k8s-cluster
  roles:
    - { role: etcd, tags: etcd }
    - { role: docker, tags: docker }
    - { role: overlay_network, tags: ['calico', 'flannel', 'network'] }
    - { role: dnsmasq, tags: dnsmasq }

- hosts: kube-master
  roles:
    - { role: kubernetes/master, tags: master }
    # Addons to be installed
    # - { role: apps/k8s-kube-ui, tags: kube-ui }
    # - { role: apps/k8s-skydns, tags: skydns }

- hosts: kube-node
  roles:
    - { role: kubernetes/node, tags: node }
