---
- hosts: downloader
  sudo: no
  roles:
    - { role: download, tags: download }

- hosts: k8s-cluster
  roles:
    - { role: etcd, tags: etcd }
    - { role: docker, tags: docker }
    - { role: overlay_network, tags: ['calico', 'flannel', 'network'] }
    - { role: dnsmasq, tags: dnsmasq }

- hosts: kube-master
  roles:
    - { role: kubernetes/master, tags: master }

- hosts: kube-node
  roles:
    - { role: kubernetes/node, tags: node }

#- hosts: kube-master
#  roles:
    # Apps to be installed
    # - { role: apps/k8s-kubedns, tags: ['kubedns', 'apps'] }
    # - { role: apps/k8s-fabric8, tags: ['fabric8', 'apps'] }
