---
- name: restart daemons
  command: /bin/true
  notify:
    - reload systemd
    - restart reloaded-kubelet
    - restart reloaded-proxy

- name: reload systemd
  command: systemctl daemon-reload

- name: restart kubelet
  command: /bin/true
  notify:
    - reload systemd
    - restart reloaded-kubelet

- name: restart reloaded-kubelet
  service:
    name: kubelet
    state: restarted

- name: restart proxy
  command: /bin/true
  notify:
    - reload systemd
    - restart reloaded-proxy

- name: restart reloaded-proxy
  service:
    name: kube-proxy
    state: restarted
