---
- name: reload systemd
  command: systemctl daemon-reload
  when: init_system == "systemd"

- name: restart kubelet
  command: /bin/true
  notify:
    - reload systemd
    - reload kubelet

- name: reload kubelet
  service:
    name: kubelet
    state: restarted
