---
- name: reload systemd
  command: systemctl daemon-reload

- name: restart systemd-kubelet
  command: /bin/true
  notify:
    - reload systemd
    - restart kubelet

- name: restart kubelet
  service:
    name: kubelet
    state: restarted
