apiVersion: "v1"
kind: "ReplicationController"
metadata: 
  annotations: {}
  labels: 
    component: "templates"
    provider: "fabric8"
  name: "templates"
spec: 
  replicas: 1
  selector: 
    component: "templates"
    provider: "fabric8"
  template: 
    metadata: 
      annotations: {}
      labels: 
        component: "templates"
        provider: "fabric8"
    spec: 
      containers: 
        - 
          args: []
          command: []
          env: 
            - 
              name: "DATA_DIR"
              value: "/data/templates"
            - 
              name: "KUBERNETES_NAMESPACE"
              valueFrom: 
                fieldRef: 
                  fieldPath: "metadata.namespace"
          image: "docker.io/fabric8/templates:2.2.19"
          name: "templates"
          ports: 
            - 
              containerPort: 8080
              name: "http"
            - 
              containerPort: 8778
              name: "jolokia"
          securityContext: {}
          volumeMounts: 
            - 
              mountPath: "/data"
              name: "template-data"
              readOnly: false
      imagePullSecrets: []
      nodeSelector: {}
      volumes: 
        - 
          gitRepo: 
            repository: "https://github.com/fabric8io/templates.git"
            revision: "master"
          name: "template-data"
