apiVersion: "v1"
kind: "Service"
metadata: 
  annotations: {}
  labels: 
    component: "templates"
    provider: "fabric8"
  name: "templates"
  namespace: "kube-system"
spec: 
  deprecatedPublicIPs: []
  ports: 
    - 
      port: 80
      protocol: "TCP"
      targetPort: 8080
  selector: 
    component: "templates"
    provider: "fabric8"
