apiVersion: "v1"
kind: "ReplicationController"
metadata: 
  annotations: {}
  labels: 
    component: "console"
    provider: "fabric8"
  name: "fabric8"
  namespace: "kube-system"
spec: 
  replicas: 1
  selector: 
    component: "console"
    provider: "fabric8"
  template: 
    metadata: 
      annotations: {}
      labels: 
        component: "console"
        provider: "fabric8"
    spec: 
      containers: 
        - 
          args: []
          command: []
          env: 
            - 
              name: "OAUTH_PROVIDER"
              value: "basic"
            - 
              name: "OAUTH_AUTHORIZE_URI"
              value: "https://vagrant.f8:8443/oauth/authorize"
            - 
              name: "GOOGLE_OAUTH_CLIENT_SECRET"
              value: ""
            - 
              name: "GOOGLE_OAUTH_REDIRECT_URI"
              value: "https://fabric8.vagrant.f8"
            - 
              name: "OAUTH_CLIENT_ID"
              value: "fabric8"
            - 
              name: "GOOGLE_OAUTH_AUTHENTICATION_URI"
              value: "https://accounts.google.com/o/oauth2/auth"
            - 
              name: "GOOGLE_OAUTH_TOKEN_URL"
              value: "https://www.googleapis.com/oauth2/v3/token"
            - 
              name: "GOOGLE_OAUTH_CLIENT_ID"
              value: ""
            - 
              name: "GOOGLE_OAUTH_SCOPE"
              value: "profile"
            - 
              name: "KUBERNETES_NAMESPACE"
              valueFrom: 
                fieldRef: 
                  fieldPath: "metadata.namespace"
          image: "docker.io/fabric8/fabric8-console:v1.0.26"
          name: "fabric8-container"
          ports: 
            - 
              containerPort: 9090
              name: "http"
          securityContext: {}
          volumeMounts: []
      imagePullSecrets: []
      nodeSelector: {}
      volumes: []
