---

# Flannel public IP
# The address that flannel should advertise as how to access the system
flannel_public_ip: "{{ access_ip|default(ip|default(ansible_default_ipv4.address)) }}"

## interface that should be used for flannel operations
## This is actually an inventory node-level item
# flannel_interface:
