- name: User | Create User Group
  group: name={{item.group|default(item.name)}} system={{item.system|default(omit)}}
  with_items: addusers

- name: User | Create User
  user:
    comment: "{{item.comment|default(omit)}}"
    createhome: "{{item.create_home|default(omit)}}"
    group: "{{item.group|default(item.name)}}"
    home: "{{item.home|default(omit)}}"
    name: "{{item.name}}"
    system: "{{item.system|default(omit)}}"
  with_items: addusers
