---
- name: restart daemons
  command: /bin/true
  notify:
    - reload systemd
    - restart apiserver
    - restart controller-manager
    - restart scheduler
    - restart proxy

- name: reload systemd
  command: systemctl daemon-reload

- name: restart apiserver
  service:
    name: kube-apiserver
    state: restarted

- name: restart controller-manager
  service:
    name: kube-controller-manager
    state: restarted

- name: restart scheduler
  service:
    name: kube-scheduler
    state: restarted

- name: restart proxy
  service:
    name: kube-proxy
    state: restarted
