---

- name: restart kube-apiserver
  command: /bin/true
  notify:
    - reload systemd
    - reload kube-apiserver

- name: reload systemd
  command: systemctl daemon-reload
  when: init_system == "systemd"

- name: reload kube-apiserver
  service:
    name: kube-apiserver
    state: restarted
