---
- name: restart daemons
  command: /bin/true
  notify:
    - reload systemd
    - restart reloaded-scheduler
    - restart reloaded-controller-manager
    - restart reloaded-apiserver
    - restart reloaded-proxy

- name: reload systemd
  command: systemctl daemon-reload

- name: restart apiserver
  command: /bin/true
  notify:
    - reload systemd
    - restart reloaded-apiserver

- name: restart reloaded-apiserver
  service:
    name: kube-apiserver
    state: restarted

- name: restart controller-manager
  command: /bin/true
  notify:
    - reload systemd
    - restart reloaded-controller-manager

- name: restart reloaded-controller-manager
  service:
    name: kube-controller-manager
    state: restarted

- name: restart scheduler
  command: /bin/true
  notify:
    - reload systemd
    - restart reloaded-scheduler

- name: restart reloaded-scheduler
  service:
    name: kube-scheduler
    state: restarted

- name: restart proxy
  command: /bin/true
  notify:
    - reload systemd
    - restart reloaded-proxy

- name: restart reloaded-proxy
  service:
    name: kube-proxy
    state: restarted
