---
- name: restart docker
  command: /bin/true
  notify:
    - reload systemd
    - restart docker service

- name: reload systemd
  shell: systemctl daemon-reload

- name: restart docker service
  service: name=docker state=restarted
