---
- name: Write kubelet systemd init file
  template: src=kubelet.service.j2 dest=/etc/systemd/system/kubelet.service backup=yes
  when: init_system == "systemd"
  notify: restart systemd-kubelet

- name: Write kubelet initd script
  template: src=deb-kubelet.initd.j2 dest=/etc/init.d/kubelet owner=root mode=755 backup=yes
  when: init_system == "sysvinit" and ansible_os_family == "Debian"
  notify: restart kubelet

- name: Write kubelet initd script
  template: src=rh-kubelet.initd.j2 dest=/etc/init.d/kubelet owner=root mode=755 backup=yes
  when: init_system == "sysvinit" and ansible_os_family == "RedHat"
  notify: restart kubelet

- name: Install kubelet binary
  copy:
     src={{ local_release_dir }}/kubernetes/bin/kubelet
     dest={{ bin_dir }}
     owner=kube
     mode=0755
  notify:
    - restart kubelet

- name: Calico-plugin | Directory
  file: path=/usr/libexec/kubernetes/kubelet-plugins/net/exec/calico/ state=directory
  when: kube_network_plugin == "calico"

- name: Calico-plugin | Binary
  copy:
    src={{ local_release_dir }}/calico/bin/calico
    dest=/usr/libexec/kubernetes/kubelet-plugins/net/exec/calico/calico
    mode=0755
  when: kube_network_plugin == "calico"
  notify: restart kubelet
