---
- name: Write kubelet systemd init file
  template: src=kubelet.service.j2 dest=/etc/systemd/system/kubelet.service backup=yes
  notify: restart kubelet

- name: Install kubelet binary
  copy:
     src={{ local_release_dir }}/kubernetes/bin/kubelet
     dest={{ bin_dir }}
     owner=kube
     mode=0755
  notify:
    - restart kubelet
