---
- name: create kubernetes config directory
  file: path={{ kube_config_dir }} state=directory

- name: create kubernetes script directory
  file: path={{ kube_script_dir }} state=directory

- name: Make sure manifest directory exists
  file: path={{ kube_manifest_dir }} state=directory

- include: secrets.yml
  tags:
    - secrets

- include: install.yml

- name: write the global config file
  template:
    src: config.j2
    dest: "{{ kube_config_dir }}/config"
  notify:
    - restart kubelet

- name: Create kubelet environment vars dir
  file: path=/etc/systemd/system/kubelet.service.d state=directory

- name: Write kubelet config file
  template: src=kubelet.j2 dest=/etc/systemd/system/kubelet.service.d/10-kubelet.conf backup=yes
  notify:
    - restart kubelet

- name: write the kubecfg (auth) file for kubelet
  template: src=node-kubeconfig.yaml.j2 dest={{ kube_config_dir }}/node-kubeconfig.yaml backup=yes
  notify:
    - restart kubelet

- name: Write proxy manifest
  template: 
    src: manifests/kube-proxy.manifest.j2
    dest: "{{ kube_manifest_dir }}/kube-proxy.manifest"

- name: Enable kubelet
  service:
    name: kubelet
    enabled: yes
    state: started

- include: temp_workaround.yml
