---
- name: define alias command for kubectl all
  lineinfile:
    dest=/etc/bash.bashrc
    line="alias kball='{{ bin_dir }}/kubectl --all-namespaces -o wide'"
    regexp='^alias kball=.*$'
    state=present
    insertafter=EOF
    create=True

- name: create kubernetes config directory
  file: path={{ kube_config_dir }} state=directory

- name: create kubernetes script directory
  file: path={{ kube_script_dir }} state=directory

- name: Make sure manifest directory exists
  file: path={{ kube_manifest_dir }} state=directory

- name: write the global config file
  template:
    src: config.j2
    dest: "{{ kube_config_dir }}/config"
  notify:
    - restart daemons

- include: secrets.yml
  tags:
    - secrets
