docker_kernel_min_version: '2.6.32-431'

docker_package_info:
  pkg_mgr: yum
  pre_pkgs:
    - epel-release
    - curl
    - device-mapper-libs
  pkgs:
    - docker-io

docker_repo_key_info:
  pkg_key: ''
  repo_keys: []

docker_repo_info:
  pkg_repo: ''
  repos: []
