---
- name: reload systemd
  command: systemctl daemon-reload

- name: restart reloaded-etcd2
  service:
    name: etcd2
    state: restarted

- name: restart etcd2
  command: /bin/true
  notify:
    - reload systemd
    - restart reloaded-etcd2
