---
- name: restart systemd-etcd
  command: /bin/true
  notify:
    - reload systemd
    - restart etcd

- name: reload systemd
  command: systemctl daemon-reload

- name: restart etcd
  service:
    name: etcd
    state: restarted
