---
- name: restart daemons
  command: /bin/true
  notify:
    - reload systemd
    - restart etcd2

- name: reload systemd
  command: systemctl daemon-reload

- name: restart etcd2
  service: name=etcd2 state=restarted

- name: Save iptables rules
  command: service iptables save
