apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx-backend
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx-backend
        tier: backend
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
        ports:
        - containerPort: 80
