apiVersion: v1
kind: Service
metadata:
  name: nginx-frontend
  labels:
    app: nginx-frontend
    tier: frontend
spec:
  externalIPs:
  - 10.210.0.12
  - 10.210.0.13
  - 10.210.0.14
  - 10.210.0.15
  - 10.210.0.16
  - 10.210.0.17
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: nginx-backend
