---
- name: Copy etcd2.service systemd file
  template:
    src: systemd-etcd2.service.j2
    dest: /lib/systemd/system/etcd2.service
    backup: yes
  notify:
    - restart etcd2

- name: Create etcd2 environment vars file
  template:
    src: etcd2-environment.j2
    dest: /etc/etcd2-environment

- name: Ensure etcd2 is running
  service: name=etcd2 state=started enabled=yes
