---
- name: INSTALL | Create etcd user
  user: name=etcd shell=/bin/nologin home=/var/lib/etcd

- name: INSTALL | Copy  etcd binaries
  synchronize:
     src: "{{ etcd_bin_dir }}/{{ item }}"
     dest: "{{ bin_dir }}"
     times: yes
     archive: no
     set_remote_user: false
  delegate_to: "{{ inventory_hostname }}"
  with_items:
    - etcdctl
    - etcd
  notify: restart etcd
