---
- name: Create etcd user
  user: name=etcd shell=/bin/nologin home=/var/lib/etcd2

- name: Install etcd binaries
  copy:
     src={{ local_release_dir }}/etcd/bin/{{ item }}
     dest={{ bin_dir }}
     owner=etcd
     mode=0755
  with_items:
    - etcdctl
    - etcd
  notify: restart etcd2

- name: Create etcd2 binary symlink
  file: src=/usr/local/bin/etcd dest=/usr/local/bin/etcd2 state=link

- name: install required python module 'httplib2'
  apt:
    name: "python-httplib2"
    state: present
  when: inventory_hostname == groups['kube-master'][0] or inventory_hostname == groups['etcd'][0]
