---
- name: ETCD2 | Stop etcd2 service
  service: name=etcd state=stopped
  ignore_errors: yes

- name: ETCD2 | create etcd pod template
  template: src=etcd-pod.yml dest=/etc/kubernetes/manifests/etcd-pod.manifest

- name: ETCD2 | Check for etcd2 port
  wait_for:
    port: 2379
    delay: 5
    timeout: 100
