apiVersion: v1
kind: Service
metadata:
  name: kubedash-frontend
  labels:
    app: kubedash-frontend
    tier: frontend
spec:
  externalIPs:
  - 10.210.0.12
  - 10.210.0.13
  - 10.210.0.14
  - 10.210.0.15
  - 10.210.0.16
  - 10.210.0.17
  ports:
  - name: http
    port: 8289
    protocol: TCP
    targetPort: 8289
  selector:
    name: kubedash
