---
local_release_dir: /tmp

# Versions
kube_version: v1.2.2
etcd_version: v2.2.5
calico_version: v0.17.0
calico_cni_version: v1.0.0
weave_version: v1.4.4

# Download URL's
kubelet_download_url: "https://storage.googleapis.com/kubespray/{{kube_version}}_kubernetes-kubelet"
apiserver_download_url: "https://storage.googleapis.com/kubespray/{{kube_version}}_kubernetes-apiserver"
kubectl_download_url: "https://storage.googleapis.com/kubespray/{{kube_version}}_kubernetes-kubectl"

etcd_download_url: "https://storage.googleapis.com/kubespray/{{etcd_version}}_etcd"
calico_download_url: "https://storage.googleapis.com/kubespray/{{calico_version}}_calico"
calico_cni_download_url: "https://storage.googleapis.com/kubespray/{{calico_cni_version}}_calico-cni-plugin"
calico_cni_ipam_download_url: "https://storage.googleapis.com/kubespray/{{calico_cni_version}}_calico-cni-plugin-ipam"
weave_download_url: "https://storage.googleapis.com/kubespray/{{weave_version}}_weave"

# Checksums
calico_checksum: "1fa22c0ee0cc661f56aa09169a3661fb46e552b53fae5fae9aac010e0666b281"
calico_cni_checksum: "cfbb95d4416cb65845a188f3bd991fff232bd5ce3463b2919d586ab77967aecd"
calico_cni_ipam_checksum: "93ebf8756b26314e1e3f612f1e824418cbb0a8df2942664422e697bcb109fbb2"
weave_checksum: "152942c330f87ab475d87d9311b91674b90f25ea685bd4e04e0495d5fe09a957"
etcd_checksum: "aa6037406257d2a1bc48ffa769afe7a4f8a04cc1ffcd36ef84f9ee8bc4eca756"
kubectl_checksum: "473e6924569fba30d4a50cecdc2cae5f31d97d1f662463e85b74a472105dcff4"
kubelet_checksum: "f16827dc7e7c82f0e215f0fc73eb01e2dfe91a2ec83f9cbcaf8d37c91b64fd3b"
kube_apiserver_checksum: "eb1bfd8b877052cbd1991b8c429a1d06661f4cb019905e20e128174f724e16de"

downloads:
  - name: calico
    dest: calico/bin/calicoctl
    version: "{{calico_version}}"
    sha256: "{{ calico_checksum }}"
    source_url: "{{ calico_download_url }}"
    url: "{{ calico_download_url }}"
    owner: "root"
    mode: "0755"

  - name: calico-cni-plugin
    dest: calico/bin/calico
    version: "{{calico_cni_version}}"
    sha256: "{{ calico_cni_checksum }}"
    source_url: "{{ calico_cni_download_url }}"
    url: "{{ calico_cni_download_url }}"
    owner: "root"
    mode: "0755"

  - name: calico-cni-plugin-ipam
    dest: calico/bin/calico-ipam
    version: "{{calico_cni_version}}"
    sha256: "{{ calico_cni_ipam_checksum }}"
    source_url: "{{ calico_cni_ipam_download_url }}"
    url: "{{ calico_cni_ipam_download_url }}"
    owner: "root"
    mode: "0755"

  - name: weave
    dest: weave/bin/weave
    version: "{{weave_version}}"
    source_url: "{{weave_download_url}}"
    url: "{{weave_download_url}}"
    sha256: "{{ weave_checksum }}"
    owner: "root"
    mode: "0755"

  - name: etcd
    version: "{{etcd_version}}"
    dest: "etcd/etcd-{{ etcd_version }}-linux-amd64.tar.gz"
    sha256: "{{ etcd_checksum }}"
    source_url: "{{ etcd_download_url }}"
    url: "{{ etcd_download_url }}"
    unarchive: true
    owner: "etcd"
    mode: "0755"

  - name: kubernetes-kubelet
    version: "{{kube_version}}"
    dest: kubernetes/bin/kubelet
    sha256: "{{kubelet_checksum}}"
    source_url: "{{ kubelet_download_url }}"
    url: "{{ kubelet_download_url }}"
    owner: "kube"
    mode: "0755"

  - name: kubernetes-kubectl
    dest: kubernetes/bin/kubectl
    version: "{{kube_version}}"
    sha256: "{{kubectl_checksum}}"
    source_url: "{{ kubectl_download_url }}"
    url: "{{ kubectl_download_url }}"
    owner: "kube"
    mode: "0755"

  - name: kubernetes-apiserver
    dest: kubernetes/bin/kube-apiserver
    version: "{{kube_version}}"
    sha256: "{{kube_apiserver_checksum}}"
    source_url: "{{ apiserver_download_url }}"
    url: "{{ apiserver_download_url }}"
    owner: "kube"
    mode: "0755"
