---
local_release_dir: /tmp

# Versions
kube_version: v1.1.7
etcd_version: v2.2.5
calico_version: v0.16.1
calico_cni_version: v1.0.0
weave_version: v1.4.4

# Download URL's
kube_download_url: "https://storage.googleapis.com/kubernetes-release/release/{{ kube_version }}/bin/linux/amd64"
etcd_download_url: "https://github.com/coreos/etcd/releases/download/{{ etcd_version }}/etcd-{{ etcd_version }}-linux-amd64.tar.gz"
calico_download_url: "https://github.com/Metaswitch/calico-docker/releases/download/{{calico_version}}/calicoctl"
calico_cni_download_url: "https://github.com/projectcalico/calico-cni/releases/download/{{calico_cni_version}}/calico"
calico_cni_ipam_download_url: "https://github.com/projectcalico/calico-cni/releases/download/{{calico_cni_version}}/calico-ipam"
weave_download_url: "https://github.com/weaveworks/weave/releases/download/{{weave_version}}/weave"

# Checksums
calico_checksum: "47f89a33325db822b590d3b2c49c3030e777a50de29e1b5289d48705ab788cc4"
calico_cni_checksum: "cfbb95d4416cb65845a188f3bd991fff232bd5ce3463b2919d586ab77967aecd"
calico_cni_ipam_checksum: "93ebf8756b26314e1e3f612f1e824418cbb0a8df2942664422e697bcb109fbb2"
weave_checksum: "152942c330f87ab475d87d9311b91674b90f25ea685bd4e04e0495d5fe09a957"
etcd_checksum: "aa6037406257d2a1bc48ffa769afe7a4f8a04cc1ffcd36ef84f9ee8bc4eca756"
kubectl_checksum: "7239fda83f0218384ccf3374a47c0d1e243975e50fdf5d544635a397c7ad10dc"
kubelet_checksum: "05faa3cf5f5448efafa553a3ef778c645c59d585d4013b52fe7ca8bd4cfc704e"
kube_apiserver_checksum: "bb73a3526e51a8f4124b42f6104103deba83f87bd985000c00d382b3a0af059a"

downloads:
  - name: calico
    dest: calico/bin/calicoctl
    sha256: "{{ calico_checksum }}"
    url: "{{ calico_download_url }}"
    owner: "root"
    mode: "0755"

  - name: calico-cni-plugin
    dest: calico/bin/calico
    sha256: "{{ calico_cni_checksum }}"
    url: "{{ calico_cni_download_url }}"
    owner: "root"
    mode: "0755"

  - name: calico-cni-plugin-ipam
    dest: calico/bin/calico-ipam
    sha256: "{{ calico_cni_ipam_checksum }}"
    url: "{{ calico_cni_ipam_download_url }}"
    owner: "root"
    mode: "0755"

  - name: weave
    dest: weave/bin/weave
    url: "{{weave_download_url}}"
    sha256: "{{ weave_checksum }}"
    owner: "root"
    mode: "0755"

  - name: etcd
    dest: "etcd/etcd-{{ etcd_version }}-linux-amd64.tar.gz"
    sha256: "{{ etcd_checksum }}"
    url: "{{ etcd_download_url }}"
    unarchive: true
    owner: "etcd"
    mode: "0755"

  - name: kubernetes-kubelet
    dest: kubernetes/bin/kubelet
    sha256: "{{kubelet_checksum}}"
    url: "{{ kube_download_url }}/kubelet"
    owner: "kube"
    mode: "0755"

  - name: kubernetes-kubectl
    dest: kubernetes/bin/kubectl
    sha256: "{{kubectl_checksum}}"
    url: "{{ kube_download_url }}/kubectl"
    owner: "kube"
    mode: "0755"

  - name: kubernetes-apiserver
    dest: kubernetes/bin/kube-apiserver
    sha256: "{{kube_apiserver_checksum}}"
    url: "{{ kube_download_url }}/kube-apiserver"
    owner: "kube"
    mode: "0755"
