---
- name: Create kubernetes binary directory
  local_action: file
     path="{{ local_release_dir }}/kubernetes/bin"
     state=directory
     recurse=yes

- name: Download kubelet and kubectl
  local_action: get_url
    url="{{ kube_download_url }}/{{ item.name }}"
    dest="{{ local_release_dir }}/kubernetes/bin"
    sha256sum="{{ item.checksum }}"
  with_items:
    - name: kubelet
      checksum: "{{ kubelet_checksum }}"
    - name: kubectl
      checksum: "{{ kubectl_checksum }}"
