---
- name: enable docker
  service:
    name: docker
    enabled: yes
    state: started
  tags:
    - docker

#- name: login to arkena's docker registry
#  shell : >
#    docker login --username={{ dockerhub_user }}
#    --password={{ dockerhub_pass }}
#    --email={{ dockerhub_email }}

- meta: flush_handlers
