---
- name: create docker service directory for systemd
  file: path=/etc/systemd/system/docker.service.d state=directory

- name: drop docker environment conf to enable proxy usage
  template:
    src: http-proxy.conf.j2
    dest: /etc/systemd/system/docker.service.d/http-proxy.conf
  register: systemddockerproxy

- name: reload systemctl daemons
  shell: systemctl daemon-reload
  when: systemddockerproxy.changed

- name: restart docker so configs are applies
  service: name=docker state=restarted
  when: systemddockerproxy.changed
