---
- name: "Test if network plugin is defined"
  fail: msg="ERROR, One network_plugin variable must be defined (Flannel or Calico)"
  when: ( kube_network_plugin is defined and kube_network_plugin == "calico" and kube_network_plugin == "flannel" ) or
        kube_network_plugin is not defined

- include: flannel.yml
  when: kube_network_plugin == "flannel"

- include: calico.yml
  when: kube_network_plugin == "calico"

- meta: flush_handlers
