---
- name: Fabric8 | Write service accounts file
  copy:
    src: fabric8-svc-accounts.yaml
    dest: "{{ kube_manifest_dir }}/fabric8-svc-accounts.yaml"
  register: fabric8_svcaccts_def

- name: Fabric8 | Write service file
  copy:
    src: fabric8-svc.yaml
    dest: "{{ kube_manifest_dir }}/fabric8-svc.yaml"
  register: fabric8_svc_def

- name: Fabric8 | templates | Write service file
  copy:
    src: fabric8-templates-svc.yaml
    dest: "{{ kube_manifest_dir }}/fabric8-templates-svc.yaml"
  register: fabric8_tmpl_svc_def

- name: Fabric8 | Write controller file
  copy:
    src: fabric8-rc.yaml
    dest: "{{ kube_manifest_dir }}/fabric8-rc.yaml"
  register: fabric8_rc_def

- name: Fabric8 | templates | Write controller file
  copy:
    src: fabric8-templates-rc.yaml
    dest: "{{ kube_manifest_dir }}/fabric8-templates-rc.yaml"
  register: fabric8_tmpl_rc_def


- name: Fabric8 | Create/update service account
  kube:
    namespace: default
    resource: serviceaccounts
    name: fabric8
    filename: "{{ kube_manifest_dir }}/fabric8-svc-accounts.yaml"
    state: "{{ fabric8_svcaccts_def.changed | ternary('latest','present') }}"
  ignore_errors: yes

- name: Fabric8 | Create/update service
  kube:
    namespace: default
    resource: svc
    name: fabric8
    filename: "{{ kube_manifest_dir }}/fabric8-svc.yaml"
    state: "{{ fabric8_svc_def.changed | ternary('latest','present') }}"

- name: Fabric8 | templates | Create/update service
  kube:
    namespace: default
    resource: svc
    name: templates
    filename: "{{ kube_manifest_dir }}/fabric8-templates-svc.yaml"
    state: "{{ fabric8_tmpl_svc_def.changed | ternary('latest','present') }}"

- name: Fabric8 | Create/update replication controller
  kube:
    namespace: default
    resource: rc
    name: fabric8
    filename: "{{ kube_manifest_dir }}/fabric8-rc.yaml"
    state: "{{ fabric8_rc_def.changed | ternary('latest','present') }}"

- name: Fabric8 | templates | Create/update replication controller
  kube:
    namespace: default
    resource: rc
    name: templates
    filename: "{{ kube_manifest_dir }}/fabric8-templates-rc.yaml"
    state: "{{ fabric8_tmpl_rc_def.changed | ternary('latest','present') }}"
