- hosts: kube-master
  pre_tasks:
    - name: Rsync nodes list
      synchronize: src=/root/nodes dest=/root/nodes
    - name: Rsync MCP scripts and repo
      synchronize:
        src: /root/ccp/
        dest: /root/ccp/
        rsync_opts:
          - "--exclude=/microservices-repos"
  tasks:
    - name: Deploy CCP
      shell: ./ccp-deploy.sh
      args:
        chdir: /root/ccp
      run_once: true
