- hosts: kube-master
  pre_tasks:
    - name: Rsync nodes list
      synchronize: src=/root/nodes dest=/root/nodes
  tasks:
    - name: Deploy CCP
      shell: ./ccp-deploy.sh
      args:
        chdir: /root/ccp
      run_once: true
