---
- name: "Test if overlay network is defined"
  fail: msg="ERROR, One overlay_network variable must be defined (Flannel or Calico)"
  when: ( overlay_network_plugin is defined and overlay_network_plugin == "calico" and overlay_network_plugin == "flannel" ) or
        overlay_network_plugin is not defined 

- include: flannel.yml
  when: overlay_network_plugin == "flannel"
- include: calico.yml
  when: overlay_network_plugin == "calico"

- meta: flush_handlers

